title: "Haktuts"

baseurl: ""
url: "https://www.haktuts.blog"

locale: de

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

collections:
  pages:
    output: true

permalink: pretty 
