name: Aktualisiere Links und Inhalte

on:
  schedule:
    - cron: '*/30 * * * *' # Läuft alle 30 Minuten
  push:
    branches:
      - main

jobs:
  update-content:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        game:
          - coin-master
          - monopoly-go
          - bingo-blitz
          - dice-dreams
          - match-masters
          - solitaire-grand-harvest
          - slotpark
          - house-of-fun
          - slotomania
          - bingo-bash
          - huuuge-casino
          - wsop
          - crazy-coin
          - gametwist

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v2

      - name: Node-Module zwischenspeichern
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Playwright-Browser installieren
        run: npx playwright install

      - name: Links abrufen und aktualisieren
        run: |
          node index-js/${{ matrix.game }}.js
          echo "Inhalt von links-json/${{ matrix.game }}.json:"
          cat links-json/${{ matrix.game }}.json
          echo "Inhalt von _includes/${{ matrix.game }}.html:"
          cat _includes/${{ matrix.game }}.html

      - name: Dynamische Beitragsinhalte generieren
        run: |
          SPIEL_NAME=${{ matrix.game }}
          SPIEL_NAME_KAPITALISIERT=$(echo "$SPIEL_NAME" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')

          ABSATZ_DATEI="_includes/${SPIEL_NAME}_post.html"
          ABSATZ="\
          ## Tägliche ${SPIEL_NAME_KAPITALISIERT}-Belohnungen – Exklusive Gratis-Links! 🎉  

          Bist du ein leidenschaftlicher ${SPIEL_NAME_KAPITALISIERT}-Spieler und möchtest dein Spielerlebnis auf das nächste Level bringen? Dann bist du hier genau richtig! Wir stellen dir täglich aktualisierte Links für Freispiele, Münzen, Chips und viele weitere exklusive Belohnungen zur Verfügung.  

          ### Warum solltest du unsere Belohnungslinks nutzen?  
          ✅ **Täglich neue Belohnungen:** Wir aktualisieren unsere Links regelmäßig, damit du keine Chance auf Gratis-Boni verpasst.  
          ✅ **100 % sicher & kostenlos:** Unsere Links stammen aus offiziellen Quellen und können völlig kostenlos eingelöst werden.  
          ✅ **Ohne Anmeldung:** Kein Registrierungszwang – klicke einfach auf den Link und sichere dir deine Belohnung!  

          **💡 Tipp:** Speichere diese Seite als Favorit und schaue täglich vorbei, um keine Belohnung zu verpassen!  

          ### Was ist ${SPIEL_NAME_KAPITALISIERT}?  
          ${SPIEL_NAME_KAPITALISIERT} ist ein fesselndes Spiel, das Millionen von Spielern weltweit begeistert. Egal, ob du höhere Level erreichen oder einfach nur den Nervenkitzel genießen möchtest – mit unseren täglichen Gratis-Links kannst du deine Chancen maximieren.  

          **Hinweis:** ${SPIEL_NAME_KAPITALISIERT} ist eine unabhängige App und steht in keiner Verbindung zu dieser Website. Unsere Links stammen aus öffentlich zugänglichen Quellen.  

          🎁 **Jetzt Belohnungen einfordern – Viel Spaß beim Spielen!** 🕹️"
          echo -e "$ABSATZ" > "$ABSATZ_DATEI"

      - name: Dynamische Footer-Inhalte generieren
        run: |
          SPIEL_NAME=${{ matrix.game }}
          SPIEL_NAME_KAPITALISIERT=$(echo "$SPIEL_NAME" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')

          FOOTER_DATEI="_includes/${SPIEL_NAME}_footer.html"
          FOOTER="\
          ### So sicherst du dir deine ${SPIEL_NAME_KAPITALISIERT}-Belohnungen 📲  

          Das Einlösen deiner täglichen Belohnungen ist kinderleicht! Folge diesen Schritten, um Freispiele, Münzen oder Chips zu erhalten:  

          1️⃣ **Belohnungslink auswählen:** Suche dir einen passenden Link aus unserer Liste oben aus.  
          2️⃣ **Klicken & Weiterleitung abwarten:** Du wirst automatisch zur offiziellen ${SPIEL_NAME_KAPITALISIERT}-App oder Website weitergeleitet.  
          3️⃣ **Anmelden & Belohnung erhalten:** Falls erforderlich, melde dich mit deinem Spielkonto an – die Belohnung wird dann sofort gutgeschrieben!  

          ### Häufige Fragen & Tipps 🧐  
          ❓ **Warum funktioniert ein Link nicht?**  
          ➡️ Einige Links haben ein Ablaufdatum. Versuche es mit einem anderen Link oder schaue morgen wieder vorbei.  

          ❓ **Wie oft kann ich Belohnungen einfordern?**  
          ➡️ Normalerweise ist jeder Link einmal pro Konto einlösbar. Wir empfehlen, täglich neue Links zu nutzen!  

          📌 **Bleib auf dem Laufenden!**  
          Speichere unsere Website in deinen Favoriten und verpasse keine neuen Bonus-Angebote. Viel Spaß beim Spielen! 🎮  

          **Hinweis:** Die bereitgestellten Links stammen aus öffentlichen Quellen. Wir sind nicht mit den Entwicklern oder Betreibern von ${SPIEL_NAME_KAPITALISIERT} verbunden."
          echo -e "$FOOTER" > "$FOOTER_DATEI"

      - name: Git konfigurieren
        run: |
          git config --global user.email "iamrohanroy00@gmail.com"
          git config --global user.name "iamrohanroy"

      - name: Änderungen committen und pushen
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git add _includes/${{ matrix.game }}_post.html _includes/${{ matrix.game }}_footer.html
          git add links-json/${{ matrix.game }}.json
          git commit -m "Aktualisiere ${SPIEL_NAME_KAPITALISIERT}-Inhalte und Links" || true
          git stash
          git pull --rebase || true
          git stash pop || true
          for i in {1..5}; do
            git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/iamrohanroy/hkts-blog.git && break
            echo "Versuch $i: Push fehlgeschlagen, erneuter Versuch in 5 Sekunden..."
            sleep 5
            git pull --rebase || true
          done
